// Generated by gencpp from file icp_registration/Laserdata.msg
// DO NOT EDIT!


#ifndef ICP_REGISTRATION_MESSAGE_LASERDATA_H
#define ICP_REGISTRATION_MESSAGE_LASERDATA_H

#include <ros/service_traits.h>


#include <icp_registration/LaserdataRequest.h>
#include <icp_registration/LaserdataResponse.h>


namespace icp_registration
{

struct Laserdata
{

typedef LaserdataRequest Request;
typedef LaserdataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Laserdata
} // namespace icp_registration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icp_registration::Laserdata > {
  static const char* value()
  {
    return "42b9e131ec346363e4c0ed69dcc07d85";
  }

  static const char* value(const ::icp_registration::Laserdata&) { return value(); }
};

template<>
struct DataType< ::icp_registration::Laserdata > {
  static const char* value()
  {
    return "icp_registration/Laserdata";
  }

  static const char* value(const ::icp_registration::Laserdata&) { return value(); }
};


// service_traits::MD5Sum< ::icp_registration::LaserdataRequest> should match
// service_traits::MD5Sum< ::icp_registration::Laserdata >
template<>
struct MD5Sum< ::icp_registration::LaserdataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icp_registration::Laserdata >::value();
  }
  static const char* value(const ::icp_registration::LaserdataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icp_registration::LaserdataRequest> should match
// service_traits::DataType< ::icp_registration::Laserdata >
template<>
struct DataType< ::icp_registration::LaserdataRequest>
{
  static const char* value()
  {
    return DataType< ::icp_registration::Laserdata >::value();
  }
  static const char* value(const ::icp_registration::LaserdataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icp_registration::LaserdataResponse> should match
// service_traits::MD5Sum< ::icp_registration::Laserdata >
template<>
struct MD5Sum< ::icp_registration::LaserdataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icp_registration::Laserdata >::value();
  }
  static const char* value(const ::icp_registration::LaserdataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icp_registration::LaserdataResponse> should match
// service_traits::DataType< ::icp_registration::Laserdata >
template<>
struct DataType< ::icp_registration::LaserdataResponse>
{
  static const char* value()
  {
    return DataType< ::icp_registration::Laserdata >::value();
  }
  static const char* value(const ::icp_registration::LaserdataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICP_REGISTRATION_MESSAGE_LASERDATA_H
