// Generated by gencpp from file icp_registration/mapdata.msg
// DO NOT EDIT!


#ifndef ICP_REGISTRATION_MESSAGE_MAPDATA_H
#define ICP_REGISTRATION_MESSAGE_MAPDATA_H

#include <ros/service_traits.h>


#include <icp_registration/mapdataRequest.h>
#include <icp_registration/mapdataResponse.h>


namespace icp_registration
{

struct mapdata
{

typedef mapdataRequest Request;
typedef mapdataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mapdata
} // namespace icp_registration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icp_registration::mapdata > {
  static const char* value()
  {
    return "f6f36abeb6c669f26830cbdd859f7c6d";
  }

  static const char* value(const ::icp_registration::mapdata&) { return value(); }
};

template<>
struct DataType< ::icp_registration::mapdata > {
  static const char* value()
  {
    return "icp_registration/mapdata";
  }

  static const char* value(const ::icp_registration::mapdata&) { return value(); }
};


// service_traits::MD5Sum< ::icp_registration::mapdataRequest> should match
// service_traits::MD5Sum< ::icp_registration::mapdata >
template<>
struct MD5Sum< ::icp_registration::mapdataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icp_registration::mapdata >::value();
  }
  static const char* value(const ::icp_registration::mapdataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icp_registration::mapdataRequest> should match
// service_traits::DataType< ::icp_registration::mapdata >
template<>
struct DataType< ::icp_registration::mapdataRequest>
{
  static const char* value()
  {
    return DataType< ::icp_registration::mapdata >::value();
  }
  static const char* value(const ::icp_registration::mapdataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icp_registration::mapdataResponse> should match
// service_traits::MD5Sum< ::icp_registration::mapdata >
template<>
struct MD5Sum< ::icp_registration::mapdataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icp_registration::mapdata >::value();
  }
  static const char* value(const ::icp_registration::mapdataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icp_registration::mapdataResponse> should match
// service_traits::DataType< ::icp_registration::mapdata >
template<>
struct DataType< ::icp_registration::mapdataResponse>
{
  static const char* value()
  {
    return DataType< ::icp_registration::mapdata >::value();
  }
  static const char* value(const ::icp_registration::mapdataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICP_REGISTRATION_MESSAGE_MAPDATA_H
