// Generated by gencpp from file icp_registration/mapdataRequest.msg
// DO NOT EDIT!


#ifndef ICP_REGISTRATION_MESSAGE_MAPDATAREQUEST_H
#define ICP_REGISTRATION_MESSAGE_MAPDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <geometry_msgs/Transform.h>

namespace icp_registration
{
template <class ContainerAllocator>
struct mapdataRequest_
{
  typedef mapdataRequest_<ContainerAllocator> Type;

  mapdataRequest_()
    : mapdata()
    , mapdata2()
    , guess()  {
    }
  mapdataRequest_(const ContainerAllocator& _alloc)
    : mapdata(_alloc)
    , mapdata2(_alloc)
    , guess(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _mapdata_type;
  _mapdata_type mapdata;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _mapdata2_type;
  _mapdata2_type mapdata2;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _guess_type;
  _guess_type guess;





  typedef boost::shared_ptr< ::icp_registration::mapdataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icp_registration::mapdataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mapdataRequest_

typedef ::icp_registration::mapdataRequest_<std::allocator<void> > mapdataRequest;

typedef boost::shared_ptr< ::icp_registration::mapdataRequest > mapdataRequestPtr;
typedef boost::shared_ptr< ::icp_registration::mapdataRequest const> mapdataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icp_registration::mapdataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icp_registration::mapdataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::icp_registration::mapdataRequest_<ContainerAllocator1> & lhs, const ::icp_registration::mapdataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mapdata == rhs.mapdata &&
    lhs.mapdata2 == rhs.mapdata2 &&
    lhs.guess == rhs.guess;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::icp_registration::mapdataRequest_<ContainerAllocator1> & lhs, const ::icp_registration::mapdataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace icp_registration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::icp_registration::mapdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icp_registration::mapdataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icp_registration::mapdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icp_registration::mapdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icp_registration::mapdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icp_registration::mapdataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icp_registration::mapdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24990172526c75f3214ed5ba01190ab9";
  }

  static const char* value(const ::icp_registration::mapdataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24990172526c75f3ULL;
  static const uint64_t static_value2 = 0x214ed5ba01190ab9ULL;
};

template<class ContainerAllocator>
struct DataType< ::icp_registration::mapdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icp_registration/mapdataRequest";
  }

  static const char* value(const ::icp_registration::mapdataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icp_registration::mapdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 mapdata\n"
"sensor_msgs/PointCloud2 mapdata2\n"
"geometry_msgs/Transform guess\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::icp_registration::mapdataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icp_registration::mapdataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapdata);
      stream.next(m.mapdata2);
      stream.next(m.guess);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mapdataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icp_registration::mapdataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icp_registration::mapdataRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapdata: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.mapdata);
    s << indent << "mapdata2: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.mapdata2);
    s << indent << "guess: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.guess);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICP_REGISTRATION_MESSAGE_MAPDATAREQUEST_H
