// Generated by gencpp from file segway_msgs/chassis_mileage_meter_fb.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_CHASSIS_MILEAGE_METER_FB_H
#define SEGWAY_MSGS_MESSAGE_CHASSIS_MILEAGE_METER_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct chassis_mileage_meter_fb_
{
  typedef chassis_mileage_meter_fb_<ContainerAllocator> Type;

  chassis_mileage_meter_fb_()
    : vehicle_meters(0)  {
    }
  chassis_mileage_meter_fb_(const ContainerAllocator& _alloc)
    : vehicle_meters(0)  {
  (void)_alloc;
    }



   typedef uint32_t _vehicle_meters_type;
  _vehicle_meters_type vehicle_meters;





  typedef boost::shared_ptr< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_mileage_meter_fb_

typedef ::segway_msgs::chassis_mileage_meter_fb_<std::allocator<void> > chassis_mileage_meter_fb;

typedef boost::shared_ptr< ::segway_msgs::chassis_mileage_meter_fb > chassis_mileage_meter_fbPtr;
typedef boost::shared_ptr< ::segway_msgs::chassis_mileage_meter_fb const> chassis_mileage_meter_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator2> & rhs)
{
  return lhs.vehicle_meters == rhs.vehicle_meters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20e9563883d4c100779f28b349b06520";
  }

  static const char* value(const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20e9563883d4c100ULL;
  static const uint64_t static_value2 = 0x779f28b349b06520ULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/chassis_mileage_meter_fb";
  }

  static const char* value(const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 vehicle_meters\n"
;
  }

  static const char* value(const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle_meters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_mileage_meter_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::chassis_mileage_meter_fb_<ContainerAllocator>& v)
  {
    s << indent << "vehicle_meters: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.vehicle_meters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_CHASSIS_MILEAGE_METER_FB_H
