// Generated by gencpp from file segway_msgs/chassis_send_eventRequest.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_CHASSIS_SEND_EVENTREQUEST_H
#define SEGWAY_MSGS_MESSAGE_CHASSIS_SEND_EVENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct chassis_send_eventRequest_
{
  typedef chassis_send_eventRequest_<ContainerAllocator> Type;

  chassis_send_eventRequest_()
    : chassis_send_event_id(0)  {
    }
  chassis_send_eventRequest_(const ContainerAllocator& _alloc)
    : chassis_send_event_id(0)  {
  (void)_alloc;
    }



   typedef int16_t _chassis_send_event_id_type;
  _chassis_send_event_id_type chassis_send_event_id;





  typedef boost::shared_ptr< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_send_eventRequest_

typedef ::segway_msgs::chassis_send_eventRequest_<std::allocator<void> > chassis_send_eventRequest;

typedef boost::shared_ptr< ::segway_msgs::chassis_send_eventRequest > chassis_send_eventRequestPtr;
typedef boost::shared_ptr< ::segway_msgs::chassis_send_eventRequest const> chassis_send_eventRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_send_event_id == rhs.chassis_send_event_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6631db6d1a2851751f3d1391c3bf0abc";
  }

  static const char* value(const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6631db6d1a285175ULL;
  static const uint64_t static_value2 = 0x1f3d1391c3bf0abcULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/chassis_send_eventRequest";
  }

  static const char* value(const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16  chassis_send_event_id\n"
;
  }

  static const char* value(const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_send_event_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_send_eventRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::chassis_send_eventRequest_<ContainerAllocator>& v)
  {
    s << indent << "chassis_send_event_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.chassis_send_event_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_CHASSIS_SEND_EVENTREQUEST_H
