// Generated by gencpp from file segway_msgs/chassis_ctrl_src_fb.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_CHASSIS_CTRL_SRC_FB_H
#define SEGWAY_MSGS_MESSAGE_CHASSIS_CTRL_SRC_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct chassis_ctrl_src_fb_
{
  typedef chassis_ctrl_src_fb_<ContainerAllocator> Type;

  chassis_ctrl_src_fb_()
    : chassis_ctrl_cmd_src(0)  {
    }
  chassis_ctrl_src_fb_(const ContainerAllocator& _alloc)
    : chassis_ctrl_cmd_src(0)  {
  (void)_alloc;
    }



   typedef uint16_t _chassis_ctrl_cmd_src_type;
  _chassis_ctrl_cmd_src_type chassis_ctrl_cmd_src;





  typedef boost::shared_ptr< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_ctrl_src_fb_

typedef ::segway_msgs::chassis_ctrl_src_fb_<std::allocator<void> > chassis_ctrl_src_fb;

typedef boost::shared_ptr< ::segway_msgs::chassis_ctrl_src_fb > chassis_ctrl_src_fbPtr;
typedef boost::shared_ptr< ::segway_msgs::chassis_ctrl_src_fb const> chassis_ctrl_src_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_ctrl_cmd_src == rhs.chassis_ctrl_cmd_src;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18f0b95c841de3c27a460820f380d2e8";
  }

  static const char* value(const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18f0b95c841de3c2ULL;
  static const uint64_t static_value2 = 0x7a460820f380d2e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/chassis_ctrl_src_fb";
  }

  static const char* value(const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 chassis_ctrl_cmd_src\n"
;
  }

  static const char* value(const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_ctrl_cmd_src);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_ctrl_src_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::chassis_ctrl_src_fb_<ContainerAllocator>& v)
  {
    s << indent << "chassis_ctrl_cmd_src: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_ctrl_cmd_src);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_CHASSIS_CTRL_SRC_FB_H
