// Generated by gencpp from file segway_msgs/chassis_mode_fb.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_CHASSIS_MODE_FB_H
#define SEGWAY_MSGS_MESSAGE_CHASSIS_MODE_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct chassis_mode_fb_
{
  typedef chassis_mode_fb_<ContainerAllocator> Type;

  chassis_mode_fb_()
    : chassis_mode(0)  {
    }
  chassis_mode_fb_(const ContainerAllocator& _alloc)
    : chassis_mode(0)  {
  (void)_alloc;
    }



   typedef uint16_t _chassis_mode_type;
  _chassis_mode_type chassis_mode;





  typedef boost::shared_ptr< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> const> ConstPtr;

}; // struct chassis_mode_fb_

typedef ::segway_msgs::chassis_mode_fb_<std::allocator<void> > chassis_mode_fb;

typedef boost::shared_ptr< ::segway_msgs::chassis_mode_fb > chassis_mode_fbPtr;
typedef boost::shared_ptr< ::segway_msgs::chassis_mode_fb const> chassis_mode_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::chassis_mode_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::chassis_mode_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_mode_fb_<ContainerAllocator2> & rhs)
{
  return lhs.chassis_mode == rhs.chassis_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::chassis_mode_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::chassis_mode_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f87ac7ac42edc7f8ac4d0909296f365a";
  }

  static const char* value(const ::segway_msgs::chassis_mode_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf87ac7ac42edc7f8ULL;
  static const uint64_t static_value2 = 0xac4d0909296f365aULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/chassis_mode_fb";
  }

  static const char* value(const ::segway_msgs::chassis_mode_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 chassis_mode\n"
;
  }

  static const char* value(const ::segway_msgs::chassis_mode_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chassis_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chassis_mode_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::chassis_mode_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::chassis_mode_fb_<ContainerAllocator>& v)
  {
    s << indent << "chassis_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chassis_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_CHASSIS_MODE_FB_H
