// Generated by gencpp from file segway_msgs/chassis_send_event.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_CHASSIS_SEND_EVENT_H
#define SEGWAY_MSGS_MESSAGE_CHASSIS_SEND_EVENT_H

#include <ros/service_traits.h>


#include <segway_msgs/chassis_send_eventRequest.h>
#include <segway_msgs/chassis_send_eventResponse.h>


namespace segway_msgs
{

struct chassis_send_event
{

typedef chassis_send_eventRequest Request;
typedef chassis_send_eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct chassis_send_event
} // namespace segway_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segway_msgs::chassis_send_event > {
  static const char* value()
  {
    return "9a406a338d005de3b96fbb5d9a0bb1bb";
  }

  static const char* value(const ::segway_msgs::chassis_send_event&) { return value(); }
};

template<>
struct DataType< ::segway_msgs::chassis_send_event > {
  static const char* value()
  {
    return "segway_msgs/chassis_send_event";
  }

  static const char* value(const ::segway_msgs::chassis_send_event&) { return value(); }
};


// service_traits::MD5Sum< ::segway_msgs::chassis_send_eventRequest> should match
// service_traits::MD5Sum< ::segway_msgs::chassis_send_event >
template<>
struct MD5Sum< ::segway_msgs::chassis_send_eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segway_msgs::chassis_send_event >::value();
  }
  static const char* value(const ::segway_msgs::chassis_send_eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segway_msgs::chassis_send_eventRequest> should match
// service_traits::DataType< ::segway_msgs::chassis_send_event >
template<>
struct DataType< ::segway_msgs::chassis_send_eventRequest>
{
  static const char* value()
  {
    return DataType< ::segway_msgs::chassis_send_event >::value();
  }
  static const char* value(const ::segway_msgs::chassis_send_eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segway_msgs::chassis_send_eventResponse> should match
// service_traits::MD5Sum< ::segway_msgs::chassis_send_event >
template<>
struct MD5Sum< ::segway_msgs::chassis_send_eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segway_msgs::chassis_send_event >::value();
  }
  static const char* value(const ::segway_msgs::chassis_send_eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segway_msgs::chassis_send_eventResponse> should match
// service_traits::DataType< ::segway_msgs::chassis_send_event >
template<>
struct DataType< ::segway_msgs::chassis_send_eventResponse>
{
  static const char* value()
  {
    return DataType< ::segway_msgs::chassis_send_event >::value();
  }
  static const char* value(const ::segway_msgs::chassis_send_eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_CHASSIS_SEND_EVENT_H
