// Generated by gencpp from file segway_msgs/error_code_fb.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ERROR_CODE_FB_H
#define SEGWAY_MSGS_MESSAGE_ERROR_CODE_FB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct error_code_fb_
{
  typedef error_code_fb_<ContainerAllocator> Type;

  error_code_fb_()
    : host_error(0)
    , central_error(0)
    , left_motor_error(0)
    , right_motor_error(0)
    , bms_error(0)  {
    }
  error_code_fb_(const ContainerAllocator& _alloc)
    : host_error(0)
    , central_error(0)
    , left_motor_error(0)
    , right_motor_error(0)
    , bms_error(0)  {
  (void)_alloc;
    }



   typedef uint32_t _host_error_type;
  _host_error_type host_error;

   typedef uint32_t _central_error_type;
  _central_error_type central_error;

   typedef uint16_t _left_motor_error_type;
  _left_motor_error_type left_motor_error;

   typedef uint16_t _right_motor_error_type;
  _right_motor_error_type right_motor_error;

   typedef uint32_t _bms_error_type;
  _bms_error_type bms_error;





  typedef boost::shared_ptr< ::segway_msgs::error_code_fb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::error_code_fb_<ContainerAllocator> const> ConstPtr;

}; // struct error_code_fb_

typedef ::segway_msgs::error_code_fb_<std::allocator<void> > error_code_fb;

typedef boost::shared_ptr< ::segway_msgs::error_code_fb > error_code_fbPtr;
typedef boost::shared_ptr< ::segway_msgs::error_code_fb const> error_code_fbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::error_code_fb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::error_code_fb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::error_code_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::error_code_fb_<ContainerAllocator2> & rhs)
{
  return lhs.host_error == rhs.host_error &&
    lhs.central_error == rhs.central_error &&
    lhs.left_motor_error == rhs.left_motor_error &&
    lhs.right_motor_error == rhs.right_motor_error &&
    lhs.bms_error == rhs.bms_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::error_code_fb_<ContainerAllocator1> & lhs, const ::segway_msgs::error_code_fb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::error_code_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::error_code_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::error_code_fb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::error_code_fb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::error_code_fb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::error_code_fb_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::error_code_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05314ca8a2228a1f9a7c00792564dc1f";
  }

  static const char* value(const ::segway_msgs::error_code_fb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05314ca8a2228a1fULL;
  static const uint64_t static_value2 = 0x9a7c00792564dc1fULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::error_code_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/error_code_fb";
  }

  static const char* value(const ::segway_msgs::error_code_fb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::error_code_fb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 host_error\n"
"uint32 central_error\n"
"uint16 left_motor_error\n"
"uint16 right_motor_error\n"
"uint32 bms_error\n"
;
  }

  static const char* value(const ::segway_msgs::error_code_fb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::error_code_fb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.host_error);
      stream.next(m.central_error);
      stream.next(m.left_motor_error);
      stream.next(m.right_motor_error);
      stream.next(m.bms_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct error_code_fb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::error_code_fb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::error_code_fb_<ContainerAllocator>& v)
  {
    s << indent << "host_error: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.host_error);
    s << indent << "central_error: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.central_error);
    s << indent << "left_motor_error: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.left_motor_error);
    s << indent << "right_motor_error: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.right_motor_error);
    s << indent << "bms_error: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bms_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ERROR_CODE_FB_H
