// Generated by gencpp from file segway_msgs/ros_set_iap_cmdActionGoal.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDACTIONGOAL_H
#define SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <segway_msgs/ros_set_iap_cmdGoal.h>

namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_set_iap_cmdActionGoal_
{
  typedef ros_set_iap_cmdActionGoal_<ContainerAllocator> Type;

  ros_set_iap_cmdActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ros_set_iap_cmdActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::segway_msgs::ros_set_iap_cmdGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ros_set_iap_cmdActionGoal_

typedef ::segway_msgs::ros_set_iap_cmdActionGoal_<std::allocator<void> > ros_set_iap_cmdActionGoal;

typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdActionGoal > ros_set_iap_cmdActionGoalPtr;
typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdActionGoal const> ros_set_iap_cmdActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e6357da1c2724385a57e6f7c07d5fdb";
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e6357da1c272438ULL;
  static const uint64_t static_value2 = 0x5a57e6f7c07d5fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_set_iap_cmdActionGoal";
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ros_set_iap_cmdGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: segway_msgs/ros_set_iap_cmdGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool   central_board_iap_enable\n"
;
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_set_iap_cmdActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_set_iap_cmdActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::segway_msgs::ros_set_iap_cmdGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDACTIONGOAL_H
