// Generated by gencpp from file segway_msgs/ros_set_remove_push_cmdRequest.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_SET_REMOVE_PUSH_CMDREQUEST_H
#define SEGWAY_MSGS_MESSAGE_ROS_SET_REMOVE_PUSH_CMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_set_remove_push_cmdRequest_
{
  typedef ros_set_remove_push_cmdRequest_<ContainerAllocator> Type;

  ros_set_remove_push_cmdRequest_()
    : ros_set_remove_push_cmd(false)  {
    }
  ros_set_remove_push_cmdRequest_(const ContainerAllocator& _alloc)
    : ros_set_remove_push_cmd(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ros_set_remove_push_cmd_type;
  _ros_set_remove_push_cmd_type ros_set_remove_push_cmd;





  typedef boost::shared_ptr< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ros_set_remove_push_cmdRequest_

typedef ::segway_msgs::ros_set_remove_push_cmdRequest_<std::allocator<void> > ros_set_remove_push_cmdRequest;

typedef boost::shared_ptr< ::segway_msgs::ros_set_remove_push_cmdRequest > ros_set_remove_push_cmdRequestPtr;
typedef boost::shared_ptr< ::segway_msgs::ros_set_remove_push_cmdRequest const> ros_set_remove_push_cmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ros_set_remove_push_cmd == rhs.ros_set_remove_push_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f56639c835e6e64b29168b150858ced";
  }

  static const char* value(const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f56639c835e6e64ULL;
  static const uint64_t static_value2 = 0xb29168b150858cedULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_set_remove_push_cmdRequest";
  }

  static const char* value(const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  ros_set_remove_push_cmd\n"
;
  }

  static const char* value(const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ros_set_remove_push_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_set_remove_push_cmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_set_remove_push_cmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "ros_set_remove_push_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ros_set_remove_push_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_SET_REMOVE_PUSH_CMDREQUEST_H
