// Generated by gencpp from file segway_msgs/ros_set_iap_cmdFeedback.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDFEEDBACK_H
#define SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_set_iap_cmdFeedback_
{
  typedef ros_set_iap_cmdFeedback_<ContainerAllocator> Type;

  ros_set_iap_cmdFeedback_()
    : iap_percent(0)  {
    }
  ros_set_iap_cmdFeedback_(const ContainerAllocator& _alloc)
    : iap_percent(0)  {
  (void)_alloc;
    }



   typedef int16_t _iap_percent_type;
  _iap_percent_type iap_percent;





  typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ros_set_iap_cmdFeedback_

typedef ::segway_msgs::ros_set_iap_cmdFeedback_<std::allocator<void> > ros_set_iap_cmdFeedback;

typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdFeedback > ros_set_iap_cmdFeedbackPtr;
typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdFeedback const> ros_set_iap_cmdFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.iap_percent == rhs.iap_percent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d75959811f859fb95f1d61fcc99a07b";
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d75959811f859fbULL;
  static const uint64_t static_value2 = 0x95f1d61fcc99a07bULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_set_iap_cmdFeedback";
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int16  iap_percent\n"
;
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.iap_percent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_set_iap_cmdFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_set_iap_cmdFeedback_<ContainerAllocator>& v)
  {
    s << indent << "iap_percent: ";
    Printer<int16_t>::stream(s, indent + "  ", v.iap_percent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDFEEDBACK_H
