// Generated by gencpp from file segway_msgs/ros_get_sw_version_cmdResponse.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_GET_SW_VERSION_CMDRESPONSE_H
#define SEGWAY_MSGS_MESSAGE_ROS_GET_SW_VERSION_CMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_get_sw_version_cmdResponse_
{
  typedef ros_get_sw_version_cmdResponse_<ContainerAllocator> Type;

  ros_get_sw_version_cmdResponse_()
    : host_version(0)
    , central_version(0)
    , motor_version(0)  {
    }
  ros_get_sw_version_cmdResponse_(const ContainerAllocator& _alloc)
    : host_version(0)
    , central_version(0)
    , motor_version(0)  {
  (void)_alloc;
    }



   typedef uint16_t _host_version_type;
  _host_version_type host_version;

   typedef uint16_t _central_version_type;
  _central_version_type central_version;

   typedef uint16_t _motor_version_type;
  _motor_version_type motor_version;





  typedef boost::shared_ptr< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ros_get_sw_version_cmdResponse_

typedef ::segway_msgs::ros_get_sw_version_cmdResponse_<std::allocator<void> > ros_get_sw_version_cmdResponse;

typedef boost::shared_ptr< ::segway_msgs::ros_get_sw_version_cmdResponse > ros_get_sw_version_cmdResponsePtr;
typedef boost::shared_ptr< ::segway_msgs::ros_get_sw_version_cmdResponse const> ros_get_sw_version_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.host_version == rhs.host_version &&
    lhs.central_version == rhs.central_version &&
    lhs.motor_version == rhs.motor_version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "933b84bbcfb5a325324cdca41b427b5e";
  }

  static const char* value(const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x933b84bbcfb5a325ULL;
  static const uint64_t static_value2 = 0x324cdca41b427b5eULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_get_sw_version_cmdResponse";
  }

  static const char* value(const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 host_version    \n"
"uint16 central_version   \n"
"uint16 motor_version\n"
;
  }

  static const char* value(const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.host_version);
      stream.next(m.central_version);
      stream.next(m.motor_version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_get_sw_version_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_get_sw_version_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "host_version: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.host_version);
    s << indent << "central_version: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.central_version);
    s << indent << "motor_version: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.motor_version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_GET_SW_VERSION_CMDRESPONSE_H
