// Generated by gencpp from file segway_msgs/ros_set_iap_cmdResult.msg
// DO NOT EDIT!


#ifndef SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDRESULT_H
#define SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segway_msgs
{
template <class ContainerAllocator>
struct ros_set_iap_cmdResult_
{
  typedef ros_set_iap_cmdResult_<ContainerAllocator> Type;

  ros_set_iap_cmdResult_()
    : iap_result(0)
    , error_code(0)  {
    }
  ros_set_iap_cmdResult_(const ContainerAllocator& _alloc)
    : iap_result(0)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef int16_t _iap_result_type;
  _iap_result_type iap_result;

   typedef int16_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> const> ConstPtr;

}; // struct ros_set_iap_cmdResult_

typedef ::segway_msgs::ros_set_iap_cmdResult_<std::allocator<void> > ros_set_iap_cmdResult;

typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdResult > ros_set_iap_cmdResultPtr;
typedef boost::shared_ptr< ::segway_msgs::ros_set_iap_cmdResult const> ros_set_iap_cmdResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator2> & rhs)
{
  return lhs.iap_result == rhs.iap_result &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator1> & lhs, const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segway_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be52641e4ba63aab27e54ebeb837880e";
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe52641e4ba63aabULL;
  static const uint64_t static_value2 = 0x27e54ebeb837880eULL;
};

template<class ContainerAllocator>
struct DataType< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segway_msgs/ros_set_iap_cmdResult";
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int16  iap_result  #3: iap_state_complete; 4: iap_state_fail; 5: iap_state_abort\n"
"int16  error_code  #When iap_result value is 4, this value represents the error code\n"
;
  }

  static const char* value(const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.iap_result);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_set_iap_cmdResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segway_msgs::ros_set_iap_cmdResult_<ContainerAllocator>& v)
  {
    s << indent << "iap_result: ";
    Printer<int16_t>::stream(s, indent + "  ", v.iap_result);
    s << indent << "error_code: ";
    Printer<int16_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGWAY_MSGS_MESSAGE_ROS_SET_IAP_CMDRESULT_H
