global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 1   ##### changed from 1.5 to 1 by jianming
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1.2
   map_type: costmap

GlobalPlanner:        
   allow_unknown:  true
